# Generated by Django 3.1.7 on 2021-04-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
